name: Terraform Destroy Pipeline

on:
  workflow_dispatch:

concurrency:
  group: terraform-deployment
  cancel-in-progress: false

jobs:
  Terraform-Infra-Destroy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    environment: terraform-destroy # Require Approval for this job using Approval gate via GitHub Environments

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      TERRAFORM_VER: 1.12.0
      TERRAFORM_PATH: ./App

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VER }}

      - name: Terraform Init
        working-directory: ${{ env.TERRAFORM_PATH }}
        run: terraform init

      - name: Terraform Destroy
        working-directory: ${{ env.TERRAFORM_PATH }}
        run: terraform destroy -var-file=terraform.tfvars -auto-approve
